# Generated by Django 4.2.26 on 2025-11-18 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100, unique=True, verbose_name='Nama Lokasi/Sensor')),
                ('api_endpoint', models.URLField(db_column='api_url', help_text='Contoh: https://xxxxx.ngrok-free.app/api/v1/latest_data', max_length=500, verbose_name='API Endpoint')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi/Catatan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Lokasi Sensor',
                'verbose_name_plural': 'Daftar Lokasi Sensor',
            },
        ),
        migrations.CreateModel(
            name='SensorDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, verbose_name='Device ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nama Device')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='SAFE_WEB.sensorlocation')),
            ],
            options={
                'verbose_name': 'Device Sensor',
                'verbose_name_plural': 'Perangkat Sensor',
                'unique_together': {('location', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_device_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Device ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('device', models.ForeignKey(blank=True, db_column='device_obj_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='SAFE_WEB.sensordevice', verbose_name='Device')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAFE_WEB.sensorlocation', verbose_name='Lokasi Sensor')),
            ],
            options={
                'verbose_name': 'Data Sensor',
                'verbose_name_plural': 'Data Sensor Historis',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_time', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Deteksi')),
                ('anomaly_type', models.CharField(max_length=100, verbose_name='Jenis Anomali')),
                ('recommendation', models.TextField(blank=True, help_text='Saran yang diberikan sistem kepada pengguna.', verbose_name='Rekomendasi Tindakan')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Sudah Diatasi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan Penanganan Operator')),
                ('data_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SAFE_WEB.sensordata', verbose_name='Titik Data Pemicu')),
            ],
            options={
                'verbose_name': 'Peringatan Anomali',
                'verbose_name_plural': 'Peringatan Anomali',
                'ordering': ['-alert_time'],
            },
        ),
    ]
